In [1]:
# 1. What is a Python library? Why ^o we use Python libraries?

'''A Python library is a collection of pre-written and reusable code modules or functions that can be imported and used 
in Python programs. Libraries provide a set of tools, functionalities, and resources that help developers efficiently
perform common tasks without having to implement everything from scratch.'''

'A Python library is a collection of pre-written and reusable code modules or functions that can be imported and used \nin Python programs. Libraries provide a set of tools, functionalities, and resources that help developers efficiently\nperform common tasks without having to implement everything from scratch.'

In [ ]:
# 2. What is the ^ifference between Numpy array an^ List

'''Numpy Array: Store data of only same type
                  NumPy arrays are more memory-efficient compared to Python lists.\


List: List store data of any type at a time'''

3. Fin^ the shape, size an^ ^imension of the following array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [6]:
import numpy as np
a = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
print("shape of array is",a.shape)
print("size of array is",a.size)
print("dimension of array is",a.ndim)

shape of array is (3, 4)
size of array is 12
dimension of array is 2


4. Write python co^e to access the first row of the following array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]

In [7]:
a = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])

a[0]

array([1, 2, 3, 4])

5. How ^o you access the element at the thir^ row an^ fourth column from the given numpy array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]

In [8]:
a = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
a[2][3]

12

6. Write code to extract all odd-indexe elements from the given numpy array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [42]:
a = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])

for i in range(len(a)):
    for j in range(len(a[i])):
        if (i+j) % 2 !=0:
            print(a[i,j],end =" ")


2 4 5 7 10 12 

In [11]:
# 7. How can you generate a ran^om 3x3 matrix with values between 0 an^ 1?
import random
np.random.randint(0,1,(3,3))

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [15]:
# 8. Describe the ^ifference between np.random.rand and np.random.randn
'''np.random.rand:

Generates random values from a uniform distribution over the interval [0, 1).
All values have an equal probability of being selected.
The distribution is uniform, meaning each value is as likely to be chosen as any other within the specified range.
Takes shape as input to generate an array of random values.'''
np.random.rand(1,2,3)

array([[[0.49797324, 0.37004372, 0.40202284],
        [0.98049319, 0.46991378, 0.22492157]]])

In [17]:
'''Generates random values from a standard normal distribution (also known as a Gaussian or normal distribution) with mean 0 
and variance 1.
The distribution is bell-shaped, with the majority of values centered around 0.
Values are more likely to be close to 0, and less likely to be far from 0, following a Gaussian distribution.
Takes shape as input to generate an array of random values.'''
np.random.randn(1,2,3)

array([[[-0.89788586,  0.363514  ,  0.75657414],
        [ 0.37816394, -0.98700963,  0.99741553]]])

 

9. Write co^e to increase the ^imension of the following array?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [18]:
a = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])

a.reshape(6,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

10. How to transpose the following array in NumPy?

[[1, 2, 3, 4]

[5, 6, 7, 8],

[9, 10, 11, 12]]

In [19]:
a = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])

a.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [21]:
a.transpose()

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

11. Consi^er the following matrix:

Matrix A2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]

Matrix B2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]


Perform the following operation using Python1
,+ I(dex wiLe multiplicatio'
]+ Matrix multiplicatio'
+ Add both the matricK
-+ Subtract matrix B from A
+ Diide Matix B by A

In [22]:
a1 = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])

a2 = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])

In [23]:
#index wise multiplication
a1*a2

array([[  1,   4,   9,  16],
       [ 25,  36,  49,  64],
       [ 81, 100, 121, 144]])

In [27]:
# matrix multiplication

Matrix multiplication not possible


(3, 4)

In [28]:
# addition

a1+a2

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24]])

In [29]:
# subtraction 

a1-a2

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [30]:
# division

a1/a2

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

12.  Which function in Numpy can be use^ to swap the byte or^er of an array?

In [ ]:
np.ndarray.byteswap

13.  What is the significance of the np.linalg.inv function?

In [ ]:
'''The np.linalg.inv function in NumPy is used to compute the inverse of a square matrix. The significance of this 
function lies in its application to solve systems of linear equations and perform various mathematical 
operations. '''

In [32]:
#14. What ^oes the np.reshape function ^o, an^ how is it use^

'''np.reshape is used change the shape of the matrix. It should take values that are multipled gives size of the original matrix
'''

# example

a = np.array([1,2,4,5,6,4])
print(a.shape)
are = a.reshape(2,3)
print(are.shape)

(6,)
(2, 3)


 15. What is broa^casting in Numpy?

'''In NumPy, broadcasting is a powerful feature that allows universal functions to operate on arrays of different shapes and sizes. It enables element-wise operations between arrays of mismatched shapes by implicitly extending smaller arrays to match the shape of larger arrays. This eliminates the need for explicit loops and makes the code more concise and readable.'''

In [33]:
import numpy as np

# Example 1: Broadcasting with a scalar
arr1 = np.array([1, 2, 3])
scalar = 5

result1 = arr1 + scalar  # Broadcasting the scalar to the array
print("Result 1:", result1)

# Example 2: Broadcasting with arrays of different shapes
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
arr3 = np.array([10, 20, 30])

result2 = arr2 + arr3  # Broadcasting the 1D array to the 2D array
print("Result 2:")
print(result2)


Result 1: [6 7 8]
Result 2:
[[11 22 33]
 [14 25 36]]
