Q= Generate a list o> R00 integers containing values between 90 to R30 and store it in the variable `int_list`.
A>ter generating the list, >ind the >ollowing:

  

  (i) Write a Python function to calculate the mean of a given list of numbers.

Create a function to find the median of a list of numbers.

  

  (ii) Develop a program to compute the mode of a list of integers.

  

  (iii) Implement a function to calculate the weighted mean of a list of values and their corresponding weights.

  

  (iv) Write a Python function to find the geometric mean of a list of positive numbers.

  

  (v) Create a program to calculate the harmonic mean of a list of values.

  

  (vi) Build a function to determine the midrange of a list of numbers (average of the minimum and maximum).

  

  (vii) Implement a Python program to find the trimmed mean of a list, excluding a certain percentage of
outliers.

In [ ]:
import random

# Generate the list of 100 integers between 90 and 130
int_list = [random.randint(90, 130) for _ in range(100)]
print(int_list)


In [ ]:
def mean(numbers):
    return sum(numbers) / len(numbers) if numbers else 0


In [ ]:
def median(numbers):
    sorted_numbers = sorted(numbers)
    n = len(sorted_numbers)
    mid = n // 2
    if n % 2 == 0:
        return (sorted_numbers[mid - 1] + sorted_numbers[mid]) / 2
    else:
        return sorted_numbers[mid]


In [ ]:
from collections import Counter

def mode(numbers):
    frequency = Counter(numbers)
    max_freq = max(frequency.values())
    modes = [k for k, v in frequency.items() if v == max_freq]
    return modes


In [ ]:
def weighted_mean(values, weights):
    if len(values) != len(weights) or not values:
        return 0
    return sum(v * w for v, w in zip(values, weights)) / sum(weights)


In [ ]:
import math

def geometric_mean(numbers):
    if not numbers:
        return 0
    product = math.prod(numbers)
    return product ** (1 / len(numbers))


In [ ]:
def harmonic_mean(numbers):
    if not numbers or any(x == 0 for x in numbers):
        return 0
    return len(numbers) / sum(1 / x for x in numbers)


In [ ]:
def midrange(numbers):
    return (min(numbers) + max(numbers)) / 2 if numbers else 0


In [ ]:
def trimmed_mean(numbers, percentage):
    if not numbers or percentage <= 0 or percentage >= 100:
        return 0
    sorted_numbers = sorted(numbers)
    trim_count = int(len(sorted_numbers) * (percentage / 100))
    trimmed_numbers = sorted_numbers[trim_count:-trim_count]
    return mean(trimmed_numbers)


 2. Generate a list o> 500 integers containing values between 200 to 300 and store it in the variable `int_list2`.
A>ter generating the list, >ind the >ollowing:


  (i) Compare the given list of visualization for the given data:

    

    1. Frequency & Gaussian distribution

    2. Frequency smoothened KDE plot

    3. Gaussian distribution & smoothened KDE plot


  (ii) Write a Python function to calculate the range of a given list of numbers.


  (iii) Create a program to find the variance and standard deviation of a list of numbers.


  (iv) Implement a function to compute the interquartile range (IQR) of a list of values.


  (v) Build a program to calculate the coefficient of variation for a dataset.

  

  (vi) Write a Python function to find the mean absolute deviation (MAD) of a list of numbers.


  (vii) Create a program to calculate the quartile deviation of a list of values.

  

  (viii) Implement a function to find the range-based coefficient of dispersion for a dataset.

In [ ]:
import random

# Generate the list of 500 integers between 200 and 300
int_list2 = [random.randint(200, 300) for _ in range(500)]
print(int_list2)


In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

# Plot frequency distribution and Gaussian distribution
plt.figure(figsize=(14, 7))

# 1. Frequency Distribution & Gaussian Distribution
plt.subplot(3, 1, 1)
sns.histplot(int_list2, kde=False, stat='density', bins=30, color='blue', label='Histogram')
sns.histplot(int_list2, kde=True, stat='density', bins=30, color='red', label='Gaussian Fit')
plt.title('Frequency Distribution & Gaussian Distribution')
plt.xlabel('Value')
plt.ylabel('Density')
plt.legend()

# 2. Smoothened KDE Plot
plt.subplot(3, 1, 2)
sns.kdeplot(int_list2, bw_adjust=0.5, fill=True, color='green')
plt.title('Frequency Smoothened KDE Plot')
plt.xlabel('Value')
plt.ylabel('Density')

# 3. Gaussian Distribution & Smoothened KDE Plot
plt.subplot(3, 1, 3)
sns.histplot(int_list2, kde=False, stat='density', bins=30, color='blue', label='Histogram')
sns.kdeplot(int_list2, bw_adjust=0.5, fill=True, color='green', label='Smoothened KDE Plot')
plt.title('Gaussian Distribution & Smoothened KDE Plot')
plt.xlabel('Value')
plt.ylabel('Density')
plt.legend()

plt.tight_layout()
plt.show()


In [ ]:
def calculate_range(numbers):
    return max(numbers) - min(numbers) if numbers else 0


In [ ]:
def variance(numbers):
    mean_val = mean(numbers)
    return sum((x - mean_val) ** 2 for x in numbers) / (len(numbers) - 1) if numbers else 0

def standard_deviation(numbers):
    return variance(numbers) ** 0.5


In [ ]:
def interquartile_range(numbers):
    sorted_numbers = sorted(numbers)
    n = len(sorted_numbers)
    q1 = sorted_numbers[n // 4]
    q3 = sorted_numbers[3 * n // 4]
    return q3 - q1


In [ ]:
def coefficient_of_variation(numbers):
    std_dev = standard_deviation(numbers)
    mean_val = mean(numbers)
    return (std_dev / mean_val) * 100 if mean_val != 0 else 0


In [ ]:
def mean_absolute_deviation(numbers):
    mean_val = mean(numbers)
    return sum(abs(x - mean_val) for x in numbers) / len(numbers) if numbers else 0


In [ ]:
def quartile_deviation(numbers):
    sorted_numbers = sorted(numbers)
    n = len(sorted_numbers)
    q1 = sorted_numbers[n // 4]
    q3 = sorted_numbers[3 * n // 4]
    return (q3 - q1) / 2


In [ ]:
def range_based_coefficient_of_dispersion(numbers):
    range_val = calculate_range(numbers)
    mean_val = mean(numbers)
    return (range_val / mean_val) * 100 if mean_val != 0 else 0


)  Write a Pthon class representing a discrete random variable with methods to calculate its expected
value and variance.
0) Implement a program to simulate the rolling o6 a 6air six-sided die and calculate the expected value and
variance o6 the outcomes.
_) Create a Pthon 6unction to generate random samples 6rom a given probabilit distribution (e.g.,
binomial, Poisson) and calculate their mean and variance.
}) Write a Pthon script to generate random numbers 6rom a Gaussian (normal) distribution and compute
the mean, variance, and standard deviation o6 the samples.

In [ ]:
# 3

class DiscreteRandomVariable:
    def __init__(self, probabilities, values):
        self.probabilities = probabilities
        self.values = values
        if len(probabilities) != len(values):
            raise ValueError("Length of probabilities and values must be the same.")
        if not all(0 <= p <= 1 for p in probabilities) or not abs(sum(probabilities) - 1) < 1e-9:
            raise ValueError("Probabilities must sum to 1 and be between 0 and 1.")
    
    def expected_value(self):
        return sum(p * v for p, v in zip(self.probabilities, self.values))
    
    def variance(self):
        mean = self.expected_value()
        return sum(p * (v - mean) ** 2 for p, v in zip(self.probabilities, self.values))

# Example usage:
probabilities = [0.1, 0.2, 0.3, 0.4]
values = [1, 2, 3, 4]
rv = DiscreteRandomVariable(probabilities, values)
print("Expected Value:", rv.expected_value())
print("Variance:", rv.variance())


In [ ]:
#4 
import random

def simulate_die_rolls(n):
    outcomes = [random.randint(1, 6) for _ in range(n)]
    mean_outcome = sum(outcomes) / n
    variance_outcome = sum((x - mean_outcome) ** 2 for x in outcomes) / n
    return mean_outcome, variance_outcome

# Example usage:
n_rolls = 1000
mean, variance = simulate_die_rolls(n_rolls)
print("Expected Value (Mean):", mean)
print("Variance:", variance)


In [ ]:
#5 
import numpy as np

def generate_samples(distribution, *params, size=1000):
    if distribution == 'binomial':
        return np.random.binomial(params[0], params[1], size)
    elif distribution == 'poisson':
        return np.random.poisson(params[0], size)
    else:
        raise ValueError("Unsupported distribution")

def mean_and_variance(samples):
    mean_val = np.mean(samples)
    variance_val = np.var(samples)
    return mean_val, variance_val

# Example usage for binomial distribution
binomial_samples = generate_samples('binomial', 10, 0.5)
print("Binomial Mean and Variance:", mean_and_variance(binomial_samples))

# Example usage for Poisson distribution
poisson_samples = generate_samples('poisson', 5)
print("Poisson Mean and Variance:", mean_and_variance(poisson_samples))


In [ ]:
#6
def gaussian_samples(mu, sigma, size=1000):
    return np.random.normal(mu, sigma, size)

def compute_statistics(samples):
    mean_val = np.mean(samples)
    variance_val = np.var(samples)
    std_dev = np.sqrt(variance_val)
    return mean_val, variance_val, std_dev

# Example usage
mu = 0
sigma = 1
gaussian_data = gaussian_samples(mu, sigma)
mean, variance, std_dev = compute_statistics(gaussian_data)
print("Gaussian Mean:", mean)
print("Gaussian Variance:", variance)
print("Gaussian Standard Deviation:", std_dev)


) Use seaborn librar to load tips dataset. Find the 6ollowing 6rom the dataset 6or the columns total_bill
and tip`:

  

  () Wrte a Python functon that calculates ther skewness.


  () Create a program that determnes whether the columns exhbt postve skewness, negatve skewness, or s
approxmately symmetrc.


  () Wrte a functon that calculates the covarance between two columns.


  (v) Implement a Python program that calculates the Pearson correlaton coeffcent between two columns.


  (v) Wrte a scrpt to vsualze the correlaton between two specfc columns n a Pandas DataFrame usng
scatter plots.

In [ ]:
#7


In [ ]:
import seaborn as sns
import pandas as pd

# Load the tips dataset
tips = sns.load_dataset('tips')
print(tips.head())


In [ ]:
import scipy.stats as stats

def calculate_skewness(series):
    return stats.skew(series)

# Calculate skewness for 'total_bill' and 'tip'
total_bill_skewness = calculate_skewness(tips['total_bill'])
tip_skewness = calculate_skewness(tips['tip'])

print(f"Skewness of 'total_bill': {total_bill_skewness}")
print(f"Skewness of 'tip': {tip_skewness}")


In [ ]:
def skewness_type(skewness):
    if skewness > 0:
        return "Positive Skewness"
    elif skewness < 0:
        return "Negative Skewness"
    else:
        return "Approximately Symmetric"

# Determine skewness type
total_bill_skewness_type = skewness_type(total_bill_skewness)
tip_skewness_type = skewness_type(tip_skewness)

print(f"Total Bill Skewness Type: {total_bill_skewness_type}")
print(f"Tip Skewness Type: {tip_skewness_type}")


In [ ]:
def calculate_covariance(series1, series2):
    return series1.cov(series2)

# Calculate covariance between 'total_bill' and 'tip'
covariance = calculate_covariance(tips['total_bill'], tips['tip'])
print(f"Covariance between 'total_bill' and 'tip': {covariance}")


In [ ]:
def calculate_pearson_correlation(series1, series2):
    return series1.corr(series2)

# Calculate Pearson correlation coefficient between 'total_bill' and 'tip'
pearson_correlation = calculate_pearson_correlation(tips['total_bill'], tips['tip'])
print(f"Pearson Correlation Coefficient between 'total_bill' and 'tip': {pearson_correlation}")


In [ ]:
import matplotlib.pyplot as plt

def plot_scatter(df, col1, col2):
    plt.figure(figsize=(10, 6))
    sns.scatterplot(data=df, x=col1, y=col2)
    plt.title(f'Scatter Plot of {col1} vs {col2}')
    plt.xlabel(col1)
    plt.ylabel(col2)
    plt.show()

# Plot scatter plot between 'total_bill' and 'tip'
plot_scatter(tips, 'total_bill', 'tip')


) Write a Pthon 6unction to calculate the probabilit densit 6unction (PDF) o6 a continuous random
variable 6or a given normal distribution.
¸) Create a program to calculate the cumulative distribution 6unction (CDF) o6 exponential distribution.
ÕÐ) Write a Pthon 6unction to calculate the probabilit mass 6unction (PMF) o6 Poisson distribution.


In [ ]:
#8
import numpy as np

def normal_pdf(x, mu, sigma):
    return (1 / (sigma * np.sqrt(2 * np.pi))) * np.exp(-0.5 * ((x - mu) / sigma) ** 2)

# Example usage:
mu = 0  # Mean
sigma = 1  # Standard deviation
x = 1.0  # Value at which to compute the PDF
pdf_value = normal_pdf(x, mu, sigma)
print(f"PDF value at x={x}: {pdf_value}")


In [ ]:
#9
def exponential_cdf(x, lambda_):
    return 1 - np.exp(-lambda_ * x)

# Example usage:
lambda_ = 1  # Rate parameter (1/mean)
x = 2.0  # Value at which to compute the CDF
cdf_value = exponential_cdf(x, lambda_)
print(f"CDF value at x={x}: {cdf_value}")


In [ ]:
#10
from scipy.special import gammaln

def poisson_pmf(k, lambda_):
    if k < 0 or lambda_ <= 0:
        raise ValueError("k must be non-negative and lambda must be positive.")
    return (lambda_ ** k * np.exp(-lambda_)) / np.math.factorial(k)

# Example usage:
lambda_ = 5  # Average rate
k = 3  # Number of occurrences
pmf_value = poisson_pmf(k, lambda_)
print(f"PMF value for k={k}: {pmf_value}")


;M A company wants to test iN a new website layout leads to a higher conversion rate (percentage oN visitors
who make a purchase). They collect data Nrom the old and new layouts to compare.


To ge<erate the data use the followi<g comma<d:

```python

import <umpy as <p

# 50 purchases out of 1000 visitors

old_layout = <p.array([1] * 50 + [0] * 950)

# 70 purchases out of 1000 visitors  

<ew_layout = <p.array([1] * 70 + [0] * 930)

  ```

Apply z-test to fi<d which layout is successful.



In [ ]:
import numpy as np
from scipy import stats

# Generate the data
old_layout = np.array([1] * 50 + [0] * 950)
new_layout = np.array([1] * 70 + [0] * 930)

# Calculate conversion rates
p_old = np.mean(old_layout)
p_new = np.mean(new_layout)

# Calculate sample sizes
n_old = len(old_layout)
n_new = len(new_layout)

# Calculate the pooled proportion
p_pooled = (np.sum(old_layout) + np.sum(new_layout)) / (n_old + n_new)

# Calculate the standard error
standard_error = np.sqrt(p_pooled * (1 - p_pooled) * (1 / n_old + 1 / n_new))

# Calculate the z-statistic
z_statistic = (p_new - p_old) / standard_error

# Calculate the p-value
p_value = 2 * (1 - stats.norm.cdf(abs(z_statistic)))

# Print the results
print(f"Old Layout Conversion Rate: {p_old:.4f}")
print(f"New Layout Conversion Rate: {p_new:.4f}")
print(f"Z-Statistic: {z_statistic:.4f}")
print(f"P-Value: {p_value:.4f}")

# Interpretation
alpha = 0.05
if p_value < alpha:
    print("Reject the null hypothesis: There is a significant difference between the old and new layouts.")
else:
    print("Fail to reject the null hypothesis: There is no significant difference between the old and new layouts.")


¤M A tutoring service claims that its program improves students' exam scores. A sample oN students who
participated in the program was taken, and their scores beNore and aNter the program were recorded.


Use the below code to ge<erate samples of respective arrays of marks:

```python

before_program = <p.array([75, 80, 85, 70, 90, 78, 92, 88, 82, 87])

after_program = <p.array([80, 85, 90, 80, 92, 80, 95, 90, 85, 88])

```

Use z-test to fi<d if the claims made by tutor are true or false.



In [ ]:
import numpy as np
from scipy import stats

# Generate the data
before_program = np.array([75, 80, 85, 70, 90, 78, 92, 88, 82, 87])
after_program = np.array([80, 85, 90, 80, 92, 80, 95, 90, 85, 88])

# Calculate the differences
differences = after_program - before_program

# Calculate the mean and standard deviation of the differences
mean_diff = np.mean(differences)
std_diff = np.std(differences, ddof=1)
n = len(differences)

# Calculate the t-statistic
t_statistic = mean_diff / (std_diff / np.sqrt(n))

# Calculate the p-value for a two-tailed test
p_value = 2 * (1 - stats.t.cdf(np.abs(t_statistic), df=n-1))

# Print the results
print(f"Mean Difference: {mean_diff:.4f}")
print(f"Standard Deviation of Differences: {std_diff:.4f}")
print(f"T-Statistic: {t_statistic:.4f}")
print(f"P-Value: {p_value:.4f}")

# Interpretation
alpha = 0.05
if p_value < alpha:
    print("Reject the null hypothesis: The tutoring program significantly improves exam scores.")
else:
    print("Fail to reject the null hypothesis: There is no significant improvement in exam scores from the tutoring program.")


;êM A pharmaceutical company wants to determine iN a new drug is eNNective in reducing blood pressure. They
conduct a study and record blood pressure measurements beNore and aNter administering the drug.


Use the below code to ge<erate samples of respective arrays of blood pressure:


```python

before_drug = <p.array([145, 150, 140, 135, 155, 160, 152, 148, 130, 138])

after_drug = <p.array([130, 140, 132, 128, 145, 148, 138, 136, 125, 130])

  ```


Impleme<t z-test to fi<d if the drug really works or <ot.

In [ ]:
import numpy as np
from scipy import stats

# Generate the data
before_drug = np.array([145, 150, 140, 135, 155, 160, 152, 148, 130, 138])
after_drug = np.array([130, 140, 132, 128, 145, 148, 138, 136, 125, 130])

# Calculate the differences
differences = after_drug - before_drug

# Calculate the mean and standard deviation of the differences
mean_diff = np.mean(differences)
std_diff = np.std(differences, ddof=1)
n = len(differences)

# Calculate the t-statistic
t_statistic = mean_diff / (std_diff / np.sqrt(n))

# Calculate the p-value for a two-tailed test
p_value = 2 * (1 - stats.t.cdf(np.abs(t_statistic), df=n-1))

# Print the results
print(f"Mean Difference: {mean_diff:.4f}")
print(f"Standard Deviation of Differences: {std_diff:.4f}")
print(f"T-Statistic: {t_statistic:.4f}")
print(f"P-Value: {p_value:.4f}")

# Interpretation
alpha = 0.05
if p_value < alpha:
    print("Reject the null hypothesis: The drug significantly reduces blood pressure.")
else:
    print("Fail to reject the null hypothesis: There is no significant reduction in blood pressure from the drug.")


In [ ]:
import numpy as np
from scipy import stats

# Generate the data
before_drug = np.array([145, 150, 140, 135, 155, 160, 152, 148, 130, 138])
after_drug = np.array([130, 140, 132, 128, 145, 148, 138, 136, 125, 130])

# Calculate the differences
differences = after_drug - before_drug

# Calculate the mean and standard deviation of the differences
mean_diff = np.mean(differences)
std_diff = np.std(differences, ddof=1)
n = len(differences)

# Calculate the z-statistic
z_statistic = mean_diff / (std_diff / np.sqrt(n))

# Calculate the p-value for a two-tailed test
p_value = 2 * (1 - stats.norm.cdf(np.abs(z_statistic)))

# Print the results
print(f"Mean Difference: {mean_diff:.4f}")
print(f"Standard Deviation of Differences: {std_diff:.4f}")
print(f"Z-Statistic: {z_statistic:.4f}")
print(f"P-Value: {p_value:.4f}")

# Interpretation
alpha = 0.05
if p_value < alpha:
    print("Reject the null hypothesis: The drug significantly reduces blood pressure.")
else:
    print("Fail to reject the null hypothesis: There is no significant reduction in blood pressure from the drug.")


In [ ]:
#14


In [ ]:
import numpy as np
from scipy import stats

# Generate the data
response_times = np.array([4.3, 3.8, 5.1, 4.9, 4.7, 4.2, 5.2, 4.5, 4.6, 4.4])

# Known value (claim)
claimed_mean = 5

# Calculate the sample mean and standard deviation
sample_mean = np.mean(response_times)
sample_std = np.std(response_times, ddof=1)
n = len(response_times)

# Calculate the t-statistic
t_statistic = (sample_mean - claimed_mean) / (sample_std / np.sqrt(n))

# Calculate the p-value for a one-tailed test
p_value = stats.t.sf(np.abs(t_statistic), df=n-1)

# Print the results
print(f"Sample Mean: {sample_mean:.2f}")
print(f"Sample Standard Deviation: {sample_std:.2f}")
print(f"T-Statistic: {t_statistic:.4f}")
print(f"P-Value: {p_value:.4f}")

# Interpretation
alpha = 0.05
if p_value < alpha:
    print("Reject the null hypothesis: The average response time is significantly less than 5 minutes.")
else:
    print("Fail to reject the null hypothesis: There is no significant evidence that the average response time is less than 5 minutes.")


In [ ]:
import numpy as np
from scipy import stats

# Generate the data
response_times = np.array([4.3, 3.8, 5.1, 4.9, 4.7, 4.2, 5.2, 4.5, 4.6, 4.4])

# Known value (claim)
claimed_mean = 5

# Calculate the sample mean and standard deviation
sample_mean = np.mean(response_times)
sample_std = np.std(response_times, ddof=1)
n = len(response_times)

# Calculate the z-statistic
z_statistic = (sample_mean - claimed_mean) / (sample_std / np.sqrt(n))

# Calculate the p-value for a one-tailed test
p_value = stats.norm.sf(np.abs(z_statistic))

# Print the results
print(f"Sample Mean: {sample_mean:.2f}")
print(f"Sample Standard Deviation: {sample_std:.2f}")
print(f"Z-Statistic: {z_statistic:.4f}")
print(f"P-Value: {p_value:.4f}")

# Interpretation
alpha = 0.05
if p_value < alpha:
    print("Reject the null hypothesis: The average response time is significantly less than 5 minutes.")
else:
    print("Fail to reject the null hypothesis: There is no significant evidence that the average response time is less than 5 minutes.")


In [ ]:
#15
import numpy as np
from scipy import stats

def perform_ab_test(layout_a_clicks, layout_b_clicks):
    # Convert lists to numpy arrays
    a = np.array(layout_a_clicks)
    b = np.array(layout_b_clicks)
    
    # Calculate means and standard deviations
    mean_a = np.mean(a)
    mean_b = np.mean(b)
    std_a = np.std(a, ddof=1)
    std_b = np.std(b, ddof=1)
    n_a = len(a)
    n_b = len(b)
    
    # Calculate the t-statistic
    pooled_var = (((n_a - 1) * std_a**2) + ((n_b - 1) * std_b**2)) / (n_a + n_b - 2)
    se = np.sqrt(pooled_var * (1/n_a + 1/n_b))
    t_statistic = (mean_a - mean_b) / se
    
    # Calculate degrees of freedom
    df = n_a + n_b - 2
    
    # Calculate the p-value
    p_value = 2 * (1 - stats.t.cdf(np.abs(t_statistic), df=df))
    
    # Print results
    print(f"Mean of Layout A: {mean_a:.2f}")
    print(f"Mean of Layout B: {mean_b:.2f}")
    print(f"Standard Deviation of Layout A: {std_a:.2f}")
    print(f"Standard Deviation of Layout B: {std_b:.2f}")
    print(f"T-Statistic: {t_statistic:.4f}")
    print(f"Degrees of Freedom: {df}")
    print(f"P-Value: {p_value:.4f}")

    # Interpretation
    alpha = 0.05
    if p_value < alpha:
        print("Reject the null hypothesis: There is a significant difference in click-through rates between the two layouts.")
    else:
        print("Fail to reject the null hypothesis: There is no significant difference in click-through rates between the two layouts.")

# Example usage
layout_a_clicks = [28, 32, 33, 29, 31, 34, 30, 35, 36, 37]
layout_b_clicks = [40, 41, 38, 42, 39, 44, 43, 41, 45, 47]

perform_ab_test(layout_a_clicks, layout_b_clicks)


In [ ]:
#16
import numpy as np
from scipy import stats

def analyze_drug_effect(existing_drug_levels, new_drug_levels):
    # Convert lists to numpy arrays
    existing = np.array(existing_drug_levels)
    new = np.array(new_drug_levels)
    
    # Calculate means and standard deviations
    mean_existing = np.mean(existing)
    mean_new = np.mean(new)
    std_existing = np.std(existing, ddof=1)
    std_new = np.std(new, ddof=1)
    n_existing = len(existing)
    n_new = len(new)
    
    # Calculate the t-statistic
    pooled_var = (((n_existing - 1) * std_existing**2) + ((n_new - 1) * std_new**2)) / (n_existing + n_new - 2)
    se = np.sqrt(pooled_var * (1/n_existing + 1/n_new))
    t_statistic = (mean_existing - mean_new) / se
    
    # Calculate degrees of freedom
    df = n_existing + n_new - 2
    
    # Calculate the p-value
    p_value = 2 * (1 - stats.t.cdf(np.abs(t_statistic), df=df))
    
    # Print results
    print(f"Mean Cholesterol Level (Existing Drug): {mean_existing:.2f}")
    print(f"Mean Cholesterol Level (New Drug): {mean_new:.2f}")
    print(f"Standard Deviation (Existing Drug): {std_existing:.2f}")
    print(f"Standard Deviation (New Drug): {std_new:.2f}")
    print(f"T-Statistic: {t_statistic:.4f}")
    print(f"Degrees of Freedom: {df}")
    print(f"P-Value: {p_value:.4f}")

    # Interpretation
    alpha = 0.05
    if p_value < alpha:
        print("Reject the null hypothesis: The new drug significantly reduces cholesterol levels compared to the existing drug.")
    else:
        print("Fail to reject the null hypothesis: There is no significant difference in cholesterol levels between the new drug and the existing drug.")

# Example usage
existing_drug_levels = [180, 182, 175, 185, 178, 176, 172, 184, 179, 183]
new_drug_levels = [170, 172, 165, 168, 175, 173, 170, 178, 172, 176]

analyze_drug_effect(existing_drug_levels, new_drug_levels)


In [44]:
##17 

In [45]:
import numpy as np
from scipy import stats

def analyze_intervention_effect(pre_intervention_scores, post_intervention_scores):
    # Convert lists to numpy arrays
    pre_scores = np.array(pre_intervention_scores)
    post_scores = np.array(post_intervention_scores)
    
    # Calculate the differences between post and pre-intervention scores
    differences = post_scores - pre_scores
    
    # Calculate mean and standard deviation of differences
    mean_diff = np.mean(differences)
    std_diff = np.std(differences, ddof=1)
    n = len(differences)
    
    # Calculate the t-statistic
    t_statistic = mean_diff / (std_diff / np.sqrt(n))
    
    # Calculate degrees of freedom
    df = n - 1
    
    # Calculate the p-value for a two-tailed test
    p_value = 2 * (1 - stats.t.cdf(np.abs(t_statistic), df=df))
    
    # Print results
    print(f"Mean Difference: {mean_diff:.2f}")
    print(f"Standard Deviation of Differences: {std_diff:.2f}")
    print(f"T-Statistic: {t_statistic:.4f}")
    print(f"Degrees of Freedom: {df}")
    print(f"P-Value: {p_value:.4f}")

    # Interpretation
    alpha = 0.05
    if p_value < alpha:
        print("Reject the null hypothesis: The educational intervention significantly improved math scores.")
    else:
        print("Fail to reject the null hypothesis: There is no significant difference in math scores before and after the intervention.")

# Example usage
pre_intervention_scores = [80, 85, 90, 75, 88, 82, 92, 78, 85, 87]
post_intervention_scores = [90, 92, 88, 92, 95, 91, 96, 93, 89, 93]

analyze_intervention_effect(pre_intervention_scores, post_intervention_scores)


Mean Difference: 7.70
Standard Deviation of Differences: 5.50
T-Statistic: 4.4284
Degrees of Freedom: 9
P-Value: 0.0017
Reject the null hypothesis: The educational intervention significantly improved math scores.


In [46]:
#18
import numpy as np
from scipy import stats

def analyze_salary_gap(male_salaries, female_salaries):
    # Convert lists to numpy arrays
    males = np.array(male_salaries)
    females = np.array(female_salaries)
    
    # Calculate means and standard deviations
    mean_male = np.mean(males)
    mean_female = np.mean(females)
    std_male = np.std(males, ddof=1)
    std_female = np.std(females, ddof=1)
    n_male = len(males)
    n_female = len(females)
    
    # Calculate the t-statistic
    pooled_var = (((n_male - 1) * std_male**2) + ((n_female - 1) * std_female**2)) / (n_male + n_female - 2)
    se = np.sqrt(pooled_var * (1/n_male + 1/n_female))
    t_statistic = (mean_male - mean_female) / se
    
    # Calculate degrees of freedom
    df = n_male + n_female - 2
    
    # Calculate the p-value
    p_value = 2 * (1 - stats.t.cdf(np.abs(t_statistic), df=df))
    
    # Print results
    print(f"Mean Salary (Male): ${mean_male:.2f}")
    print(f"Mean Salary (Female): ${mean_female:.2f}")
    print(f"Standard Deviation (Male): ${std_male:.2f}")
    print(f"Standard Deviation (Female): ${std_female:.2f}")
    print(f"T-Statistic: {t_statistic:.4f}")
    print(f"Degrees of Freedom: {df}")
    print(f"P-Value: {p_value:.4f}")

    # Interpretation
    alpha = 0.05
    if p_value < alpha:
        print("Reject the null hypothesis: There is a significant gender-based salary gap.")
    else:
        print("Fail to reject the null hypothesis: There is no significant gender-based salary gap.")

# Generate synthetic salary data
np.random.seed(0)  # For reproducibility

male_salaries = np.random.normal(loc=50000, scale=10000, size=20)
female_salaries = np.random.normal(loc=55000, scale=9000, size=20)

# Analyze the salary gap
analyze_salary_gap(male_salaries, female_salaries)


Mean Salary (Male): $55693.35
Mean Salary (Female): $55501.75
Standard Deviation (Male): $8722.69
Standard Deviation (Female): $10968.10
T-Statistic: 0.0611
Degrees of Freedom: 38
P-Value: 0.9516
Fail to reject the null hypothesis: There is no significant gender-based salary gap.


In [47]:
#19


In [48]:
import numpy as np
from scipy import stats

def analyze_quality_scores(version1_scores, version2_scores):
    # Convert lists to numpy arrays
    version1 = np.array(version1_scores)
    version2 = np.array(version2_scores)
    
    # Calculate means and standard deviations
    mean_v1 = np.mean(version1)
    mean_v2 = np.mean(version2)
    std_v1 = np.std(version1, ddof=1)
    std_v2 = np.std(version2, ddof=1)
    n_v1 = len(version1)
    n_v2 = len(version2)
    
    # Calculate the t-statistic
    pooled_var = (((n_v1 - 1) * std_v1**2) + ((n_v2 - 1) * std_v2**2)) / (n_v1 + n_v2 - 2)
    se = np.sqrt(pooled_var * (1/n_v1 + 1/n_v2))
    t_statistic = (mean_v1 - mean_v2) / se
    
    # Calculate degrees of freedom
    df = n_v1 + n_v2 - 2
    
    # Calculate the p-value
    p_value = 2 * (1 - stats.t.cdf(np.abs(t_statistic), df=df))
    
    # Print results
    print(f"Mean Quality Score (Version 1): {mean_v1:.2f}")
    print(f"Mean Quality Score (Version 2): {mean_v2:.2f}")
    print(f"Standard Deviation (Version 1): {std_v1:.2f}")
    print(f"Standard Deviation (Version 2): {std_v2:.2f}")
    print(f"T-Statistic: {t_statistic:.4f}")
    print(f"Degrees of Freedom: {df}")
    print(f"P-Value: {p_value:.4f}")

    # Interpretation
    alpha = 0.05
    if p_value < alpha:
        print("Reject the null hypothesis: There is a significant difference in quality between the two versions.")
    else:
        print("Fail to reject the null hypothesis: There is no significant difference in quality between the two versions.")

# Example data
version1_scores = [85, 88, 82, 89, 87, 84, 90, 88, 85, 86, 91, 83, 87, 84, 89, 86, 84, 88, 85, 86, 89, 90, 87, 88, 85]
version2_scores = [80, 78, 83, 81, 79, 82, 76, 80, 78, 81, 77, 82, 80, 79, 82, 79, 80, 81, 79, 82, 79, 78, 80, 81, 82]

# Analyze the quality scores
analyze_quality_scores(version1_scores, version2_scores)


Mean Quality Score (Version 1): 86.64
Mean Quality Score (Version 2): 79.96
Standard Deviation (Version 1): 2.36
Standard Deviation (Version 2): 1.77
T-Statistic: 11.3258
Degrees of Freedom: 48
P-Value: 0.0000
Reject the null hypothesis: There is a significant difference in quality between the two versions.


In [49]:
#20
import numpy as np
from scipy import stats

def analyze_customer_satisfaction(branch_a_scores, branch_b_scores):
    # Convert lists to numpy arrays
    branch_a = np.array(branch_a_scores)
    branch_b = np.array(branch_b_scores)
    
    # Calculate means and standard deviations
    mean_a = np.mean(branch_a)
    mean_b = np.mean(branch_b)
    std_a = np.std(branch_a, ddof=1)
    std_b = np.std(branch_b, ddof=1)
    n_a = len(branch_a)
    n_b = len(branch_b)
    
    # Calculate the t-statistic
    pooled_var = (((n_a - 1) * std_a**2) + ((n_b - 1) * std_b**2)) / (n_a + n_b - 2)
    se = np.sqrt(pooled_var * (1/n_a + 1/n_b))
    t_statistic = (mean_a - mean_b) / se
    
    # Calculate degrees of freedom
    df = n_a + n_b - 2
    
    # Calculate the p-value
    p_value = 2 * (1 - stats.t.cdf(np.abs(t_statistic), df=df))
    
    # Print results
    print(f"Mean Satisfaction Score (Branch A): {mean_a:.2f}")
    print(f"Mean Satisfaction Score (Branch B): {mean_b:.2f}")
    print(f"Standard Deviation (Branch A): {std_a:.2f}")
    print(f"Standard Deviation (Branch B): {std_b:.2f}")
    print(f"T-Statistic: {t_statistic:.4f}")
    print(f"Degrees of Freedom: {df}")
    print(f"P-Value: {p_value:.4f}")

    # Interpretation
    alpha = 0.05
    if p_value < alpha:
        print("Reject the null hypothesis: There is a significant difference in customer satisfaction between the two branches.")
    else:
        print("Fail to reject the null hypothesis: There is no significant difference in customer satisfaction between the two branches.")

# Example data
branch_a_scores = [4, 5, 3, 4, 5, 4, 5, 3, 4, 4, 5, 4, 4, 3, 4, 5, 5, 4, 3, 4, 5, 4, 3, 5, 4, 4, 5, 3, 4, 5, 4]
branch_b_scores = [3, 4, 2, 3, 4, 3, 4, 2, 3, 3, 4, 3, 3, 2, 3, 4, 4, 3, 2, 3, 4, 3, 2, 4, 3, 3, 4, 2, 3, 4, 3]

# Analyze the customer satisfaction scores
analyze_customer_satisfaction(branch_a_scores, branch_b_scores)


Mean Satisfaction Score (Branch A): 4.13
Mean Satisfaction Score (Branch B): 3.13
Standard Deviation (Branch A): 0.72
Standard Deviation (Branch B): 0.72
T-Statistic: 5.4801
Degrees of Freedom: 60
P-Value: 0.0000
Reject the null hypothesis: There is a significant difference in customer satisfaction between the two branches.


In [50]:
#21
import numpy as np
import pandas as pd
from scipy import stats

# Generate synthetic data
np.random.seed(0)
age_groups = np.random.choice(['18-30', '31-50', '51+'], size=500)
voter_preferences = np.random.choice(['Candidate A', 'Candidate B'], size=500)

# Create a DataFrame
data = pd.DataFrame({'Age Group': age_groups, 'Voter Preference': voter_preferences})

# Create a contingency table
contingency_table = pd.crosstab(data['Age Group'], data['Voter Preference'])

# Perform the Chi-Square test
chi2_stat, p_value, dof, expected = stats.chi2_contingency(contingency_table)

# Print results
print("Contingency Table:")
print(contingency_table)
print("\nChi-Square Statistic:", chi2_stat)
print("Degrees of Freedom:", dof)
print("P-Value:", p_value)

# Interpretation
alpha = 0.05
if p_value < alpha:
    print("Reject the null hypothesis: There is a significant association between age groups and voter preferences.")
else:
    print("Fail to reject the null hypothesis: There is no significant association between age groups and voter preferences.")


Contingency Table:
Voter Preference  Candidate A  Candidate B
Age Group                                 
18-30                      95           87
31-50                      87           82
51+                        84           65

Chi-Square Statistic: 0.8779923945254768
Degrees of Freedom: 2
P-Value: 0.6446832311860852
Fail to reject the null hypothesis: There is no significant association between age groups and voter preferences.


In [51]:
#22
import numpy as np
from scipy import stats

# Sample data: Product satisfaction levels (rows) vs. Customer regions (columns)
data = np.array([[50, 30, 40, 20], 
                 [30, 40, 30, 50], 
                 [20, 30, 40, 30]])

# Perform the Chi-Square test
chi2_stat, p_value, dof, expected = stats.chi2_contingency(data)

# Print results
print("Contingency Table:")
print(data)
print("\nChi-Square Statistic:", chi2_stat)
print("Degrees of Freedom:", dof)
print("P-Value:", p_value)
print("Expected Frequencies:")
print(expected)

# Interpretation
alpha = 0.05
if p_value < alpha:
    print("Reject the null hypothesis: There is a significant relationship between product satisfaction levels and customer regions.")
else:
    print("Fail to reject the null hypothesis: There is no significant relationship between product satisfaction levels and customer regions.")


Contingency Table:
[[50 30 40 20]
 [30 40 30 50]
 [20 30 40 30]]

Chi-Square Statistic: 27.777056277056275
Degrees of Freedom: 6
P-Value: 0.00010349448486004387
Expected Frequencies:
[[34.14634146 34.14634146 37.56097561 34.14634146]
 [36.58536585 36.58536585 40.24390244 36.58536585]
 [29.26829268 29.26829268 32.19512195 29.26829268]]
Reject the null hypothesis: There is a significant relationship between product satisfaction levels and customer regions.


In [52]:
#23
import numpy as np
from scipy import stats

# Sample data: Job performance levels before (rows) and after (columns) training
data = np.array([[50, 30, 20], 
                 [30, 40, 30], 
                 [20, 30, 40]])

# Perform the Chi-Square test
chi2_stat, p_value, dof, expected = stats.chi2_contingency(data)

# Print results
print("Contingency Table:")
print(data)
print("\nChi-Square Statistic:", chi2_stat)
print("Degrees of Freedom:", dof)
print("P-Value:", p_value)
print("Expected Frequencies:")
print(expected)

# Interpretation
alpha = 0.05
if p_value < alpha:
    print("Reject the null hypothesis: There is a significant difference in job performance levels before and after the training.")
else:
    print("Fail to reject the null hypothesis: There is no significant difference in job performance levels before and after the training.")


Contingency Table:
[[50 30 20]
 [30 40 30]
 [20 30 40]]

Chi-Square Statistic: 22.161728395061726
Degrees of Freedom: 4
P-Value: 0.00018609719479882557
Expected Frequencies:
[[34.48275862 34.48275862 31.03448276]
 [34.48275862 34.48275862 31.03448276]
 [31.03448276 31.03448276 27.93103448]]
Reject the null hypothesis: There is a significant difference in job performance levels before and after the training.


In [53]:
#24
import numpy as np
from scipy import stats

# Sample data: Customer satisfaction scores for each product version
standard_scores = [80, 85, 90, 78, 88, 82, 92, 78, 85, 87]
premium_scores = [90, 92, 88, 92, 95, 91, 96, 93, 89, 93]
deluxe_scores = [95, 98, 92, 97, 96, 94, 98, 97, 92, 99]

# Perform the ANOVA test
f_statistic, p_value = stats.f_oneway(standard_scores, premium_scores, deluxe_scores)

# Print results
print("ANOVA Test Results")
print("F-Statistic:", f_statistic)
print("P-Value:", p_value)

# Interpretation
alpha = 0.05
if p_value < alpha:
    print("Reject the null hypothesis: There is a significant difference in customer satisfaction scores among the product versions.")
else:
    print("Fail to reject the null hypothesis: There is no significant difference in customer satisfaction scores among the product versions.")


ANOVA Test Results
F-Statistic: 27.03556231003039
P-Value: 3.5786328857349003e-07
Reject the null hypothesis: There is a significant difference in customer satisfaction scores among the product versions.
